import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, shadow } from '../theme';
import { useBookingStore } from '../store/useBookingStore';
import { createFirebaseWaitlist, deleteFirebaseWaitlist, isFirebaseConfigured } from '../services/firebase';
import { dateLabel, getNextSevenDays, isSeedBooked, rooms, timeSlots } from '../data/mockData';

type RootStackParamList = { AppTabs: undefined; RoomDetail: { roomId: string }; Waitlist: undefined };
type Props = NativeStackScreenProps<RootStackParamList, 'Waitlist'>;

export function WaitlistScreen({ navigation }: Props) {
  const waitlist = useBookingStore((state) => state.waitlist);
  const leaveWaitlist = useBookingStore((state) => state.leaveWaitlist);
  const joinWaitlist = useBookingStore((state) => state.joinWaitlist);
  const [roomId, setRoomId] = useState(rooms[0].id);
  const [dayIndex, setDayIndex] = useState(0);
  const [slotId, setSlotId] = useState(timeSlots[0].id);
  const days = getNextSevenDays();
  const selectedRoom = rooms.find((room) => room.id === roomId) || rooms[0];
  const selectedDay = days[dayIndex];
  const join = () => { const slot = timeSlots.find((item) => item.id === slotId) || timeSlots[0]; const entry = joinWaitlist({ roomId: selectedRoom.id, roomName: selectedRoom.name, building: selectedRoom.building, dateKey: `${selectedDay.getFullYear()}-${String(selectedDay.getMonth() + 1).padStart(2, '0')}-${String(selectedDay.getDate()).padStart(2, '0')}`, dateLabel: dateLabel(selectedDay), slotId: slot.id, slotLabel: slot.label }); if (isFirebaseConfigured) void createFirebaseWaitlist(entry).catch(() => undefined); Alert.alert('Đã vào danh sách chờ', `${selectedRoom.name} · ${slot.label}`); };
  return <SafeAreaView style={styles.screen} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.iconButton} accessibilityLabel="Quay lại"><Ionicons name="arrow-back" size={22} color={colors.ink} /></Pressable><View style={styles.headerCopy}><Text style={styles.kicker}>WAITLIST</Text><Text style={styles.title}>Danh sách chờ</Text></View></View>
    <Text style={styles.subtitle}>Khi có người hủy, bạn sẽ được ưu tiên thông báo để giữ slot.</Text>
    <View style={styles.formCard}><Text style={styles.formTitle}>Tạo yêu cầu chờ</Text><Text style={styles.fieldLabel}>Chọn phòng</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{rooms.slice(0, 6).map((room) => <Pressable key={room.id} onPress={() => setRoomId(room.id)} style={[styles.chip, roomId === room.id && styles.chipActive]}><Text style={[styles.chipText, roomId === room.id && styles.chipTextActive]}>{room.name}</Text></Pressable>)}</ScrollView><Text style={styles.fieldLabel}>Chọn ngày</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{days.map((day, index) => <Pressable key={day.toISOString()} onPress={() => setDayIndex(index)} style={[styles.chip, dayIndex === index && styles.chipActive]}><Text style={[styles.chipText, dayIndex === index && styles.chipTextActive]}>{index === 0 ? 'Hôm nay' : dateLabel(day)}</Text></Pressable>)}</ScrollView><Text style={styles.fieldLabel}>Chọn slot</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{timeSlots.map((slot) => <Pressable key={slot.id} onPress={() => setSlotId(slot.id)} style={[styles.chip, slotId === slot.id && styles.chipActive, isSeedBooked(selectedRoom.id, selectedDay, slot.id) && styles.busyChip]}><Text style={[styles.chipText, slotId === slot.id && styles.chipTextActive]}>{slot.label}</Text></Pressable>)}</ScrollView><Text style={styles.formHint}>Bạn có thể chờ slot đã kín hoặc đang có người sử dụng.</Text><Pressable onPress={join} style={styles.primaryButton}><Ionicons name="hourglass-outline" size={18} color={colors.white} /><Text style={styles.primaryButtonText}>Tham gia danh sách chờ</Text></Pressable></View>
    {waitlist.length === 0 ? <View style={styles.empty}><Ionicons name="hourglass-outline" size={35} color={colors.primary} /><Text style={styles.emptyTitle}>Chưa có yêu cầu chờ</Text><Text style={styles.emptyText}>Mở một phòng, chọn ngày và slot đã kín để tham gia danh sách chờ.</Text></View> : waitlist.map((entry) => <View style={styles.card} key={entry.id}><View style={styles.cardIcon}><Ionicons name="hourglass-outline" size={20} color={colors.primary} /></View><View style={styles.cardCopy}><Text style={styles.roomName}>{entry.roomName}</Text><Text style={styles.meta}>{`${entry.dateLabel} · ${entry.slotLabel}`}</Text><Text style={styles.status}>{entry.status === 'notified' ? 'Có slot trống - hãy đặt ngay' : 'Đang chờ thông báo'}</Text></View><Pressable onPress={() => Alert.alert('Rời danh sách chờ?', `${entry.roomName} · ${entry.slotLabel}`, [{ text: 'Ở lại', style: 'cancel' }, { text: 'Rời đi', style: 'destructive', onPress: () => { leaveWaitlist(entry.id); if (isFirebaseConfigured) void deleteFirebaseWaitlist(entry.id).catch(() => undefined); } }])} style={styles.removeButton} accessibilityLabel={`Rời danh sách chờ ${entry.roomName}`}><Ionicons name="close" size={18} color={colors.danger} /></Pressable></View>)}
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.skySoft }, content: { padding: 20, paddingBottom: 120 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headerCopy: { flex: 1 }, iconButton: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, kicker: { color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 27, fontWeight: '800', marginTop: 4 }, subtitle: { color: colors.inkMuted, fontSize: 14, lineHeight: 21, marginTop: 16, marginBottom: 20 }, formCard: { backgroundColor: colors.white, borderRadius: 18, padding: 16, marginBottom: 20, ...shadow.card }, formTitle: { color: colors.ink, fontSize: 16, fontWeight: '800', marginBottom: 14 }, fieldLabel: { color: colors.ink, fontSize: 11, fontWeight: '800', marginTop: 7, marginBottom: 7 }, chips: { gap: 8, paddingRight: 12, paddingBottom: 3 }, chip: { minHeight: 38, borderRadius: 999, paddingHorizontal: 12, backgroundColor: colors.surfaceMuted, justifyContent: 'center', borderWidth: 1, borderColor: colors.line }, busyChip: { borderColor: colors.amber }, chipActive: { backgroundColor: colors.ink, borderColor: colors.ink }, chipText: { color: colors.inkMuted, fontSize: 11, fontWeight: '800' }, chipTextActive: { color: colors.white }, formHint: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginTop: 10 }, primaryButton: { minHeight: 50, borderRadius: 14, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 14 }, primaryButtonText: { color: colors.white, fontWeight: '800', fontSize: 13 }, card: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.white, borderRadius: 18, padding: 13, marginBottom: 11, ...shadow.card }, cardIcon: { width: 43, height: 43, borderRadius: 14, backgroundColor: colors.sky, alignItems: 'center', justifyContent: 'center' }, cardCopy: { flex: 1 }, roomName: { color: colors.ink, fontSize: 15, fontWeight: '800' }, meta: { color: colors.inkMuted, fontSize: 12, marginTop: 4 }, status: { color: colors.amber, fontSize: 11, fontWeight: '800', marginTop: 6 }, removeButton: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.dangerSoft, alignItems: 'center', justifyContent: 'center' }, empty: { alignItems: 'center', backgroundColor: colors.white, borderRadius: 20, padding: 30, marginTop: 10, ...shadow.card }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 13, textAlign: 'center' }, emptyText: { color: colors.inkMuted, fontSize: 13, lineHeight: 20, marginTop: 7, textAlign: 'center' } });
